[theme]
primaryColor = "#ff005a"    # PL Pink for buttons and highlights
backgroundColor = "#37003C"  # Deep black for the main background
secondaryBackgroundColor = "#4E0055" #PL Purple for sidebar and containers
textColor = "#ffffff"       # White text for readability
font = "sans serif"
#"#28002B"
#ff005a
#"#4E0055"